

[battery]
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "
disabled = false

[erlang]
symbol = "‚ìî "

[git_branch]
ignore_branches = ['master', 'main']

[git_metrics]
disabled = false
format = '[+$added]($added_style) [-$deleted]($deleted_style) '

[nodejs]
symbol = "[‚¨¢](bold green) "

[pulumi]
symbol = "üßä "

[hostname]
ssh_only = false
format = '@[$hostname](purple) '
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[shell]
disabled = false
fish_indicator = ""
zsh_indicator = '\[zsh\]'
